logo:
  icon: /images/icon.ico
  title: ZalexK

inject:
  head:
    - <link href="https://fonts.googleapis.com/css2?family=Noto+Serif+SC&display=swap" rel="stylesheet">
  script:


menubar:
  items: []
site_tree:
  home:
    sidebar: starter, welcome, recent
  index_blog:
    sidebar: starter, welcome, recent
  index_topic:
    menu_id: topic
  topic:
    menu_id: topic

article:
  share: [link]
  auto_cover: false

style:
  border-radius:
    bar: 4px
    card: 4px
    block: 4px

  font-family:
    body: '"Noto Serif SC", "Microsoft Yahei",..., sans-serif'

