logo:
  icon: /images/icon.ico
  title: ZalexK

preconnect:
  - https://fonts.gstatic.com
  - https://fonts.googleapis.com

inject:
  head:
    - <link href="https://fonts.googleapis.com/css2?family=LXGW+WenKai+Mono+TC:wght@400;700&family=LXGW+WenKai+TC:wght@400;700&display=swap" rel="stylesheet">
menubar:
  items: []
site_tree:
  home:
    sidebar: starter, welcome, recent
  index_blog:
    sidebar: starter, welcome, recent
  index_topic:
    menu_id: topic
  topic:
    menu_id: topic

article:
  share: [link]
  auto_cover: false

style:
  text-align: justify

  smooth_scroll: false

  codeblock:
    scrollbar: 0px

  font-size:
    body: 1rem

  font-family:
    logo: '"LXGW WenKai TC", system-ui, "Microsoft Yahei", "Segoe UI", -apple-system, Roboto, Ubuntu, "Helvetica Neue", Arial, "WenQuanYi Micro Hei", sans-serif'
    body: '"LXGW WenKai TC", system-ui, "Microsoft Yahei", "Segoe UI", -apple-system, Roboto, Ubuntu, "Helvetica Neue", Arial, "WenQuanYi Micro Hei", sans-serif'
    code: '"LXGW WenKai Mono TC", Menlo, Monaco, Consolas, system-ui, "Courier New", monospace, sans-serif'
    codeblock: 'Menlo, Monaco, Consolas, system-ui, "Courier New", monospace, sans-serif'

# 文章搜索
search:
  service: local_search # local_search, todo...
  local_search:
    field: all # post, page, all
    path: /search.json # 搜索文件存放位置
    content: true # 是否搜索内容
    skip_search: [] # 指定 path 中的内容不被搜索。
    codeblock: true # 是否搜索代码块（需要content: true)
